apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cobaingress-development"
  annotations:
    cattle.io/timestamp: "2021-02-15T10:15:27.619Z"
  labels:
    app: "cobaingress-development"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cobaingress-development"
  template:
    metadata:
      labels:
        app: "cobaingress-development"
    spec:
      dnsPolicy: "ClusterFirst"
      restartPolicy: "Always"      
      containers:
        - name: "cobaingress-development"
          image: "frostmarry/dumbflix-be:v2"
          env:
            - name: "MICROGEN_SERVICES"
              value: "main,user"
            - name: "COTE_LOG"
              value: "false"
            - name: "COTE_LOG_UNKNOWN_EVENTS"
              value: "false"
            - name: "COTE_REQUEST_TIMEOUT"
              value: "300000"
            - name: "COTE_MULTICAST_ADDRESS"
              value: "239.1.11.131"
            - name: "DISCOVERY_HOSTNAME"
              valueFrom:
                fieldRef:
                  apiVersion: "v1"
                  fieldPath: "status.podIP"
          ports:
            - containerPort: 5000
              name: "5000tcp1"
              protocol: "TCP"

---

apiVersion: "v1"
kind: "Service"
metadata:
  name: "cobaingress-development"
  labels:
    app: "cobaingress-development"
spec:
  type: "NodePort"
  ports:
    - port: 5000
  selector:
    app: "cobaingress-development"

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: 2021-02-15T10:15:27.623Z
  generation: 1
  labels:
    app: cobaingress-development
  name: cobaingress-development
  namespace: default
    - clusterId: fleet-default/c-kdkrk
      patch:
        metadata:
          generation: 1
        spec:
          rules:
          - host: coba.sigmatech.microgen.id
            http:
              paths:
              - backend:
                  serviceName: cobaingress-development
                  servicePort: 5000
                pathType: ImplementationSpecific
        tls:
        - secretName: microgen-sigmatech
      state: Modified
    - clusterId: fleet-default/c-nsg6f
      patch:
        metadata:
          generation: 1
        spec:
          rules:
          - host: coba.aws.sigmatech.microgen.id
            http:
              paths:
              - backend:
                  serviceName: cobaingress-development
                  servicePort: 5000
                pathType: ImplementationSpecific
          tls:
          - secretName: aws
# spec:
#   rules:
#     - host: xip.io
#       http:
#         paths:
#           - backend:
#               serviceName: cobaingress-development
#               servicePort: 5000
#             pathType: ImplementationSpecific
status:
  loadBalancer: {}
