apiVersion: extensions/v1beta1
kind: Ingress
metadata:  
  clusterName: aws
  creationTimestamp: 2021-02-15T10:15:27.623Z
  generation: 1
  labels:
    app: cobaingress-development
  name: cobaingress-development
  namespace: default
spec:
  tls:
    - hosts:
      - coba.{{ .Values.host }}
      secretName: {{ .Values.ssl }}
  rules:
    - host: coba.{{ .Values.host }}
      http:
        paths:
          - backend:
              serviceName: cobaingress-development
              servicePort: 5000
            pathType: ImplementationSpecific
status:
  loadBalancer: {}
