apiVersion: "v1"
kind: "Service"
metadata:
  name: "cobaingress-development"
  labels:
    app: "cobaingress-development"
spec:
  type: "NodePort"
  ports:
    - port: 5000
  selector:
    app: "cobaingress-development"
